testing actions and related files temporarily on the public repository

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,27 +5,32 @@ on:
 
 jobs:
   build:
+    strategy:
+      matrix:
+        python-version: [3.11.5, 3.10.13, 3.9.17, 3.8.17] #3.8.17 Test avec plusieurs versions de Python
+
     runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v3
 
-    - name: Set up Python 3.10.14
+    - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v4
       with:
-        python-version: '3.10.14'  # Spécifiez la version de Python que vous utilisez
+        python-version: ${{ matrix.python-version }}
 
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -r requirements.txt  # Assurez-vous d'avoir un fichier requirements.txt avec les dépendances nécessaires
+        pip install -r requirements.txt  # Installer les dépendances
 
     - name: Check pytest installation
-      run: pytest --version  # Vérifiez que pytest est bien installé
+      run: pytest --version
 
-    - name: List files for debugging
-      run: ls -R  # Liste tous les fichiers pour s'assurer que les fichiers de test sont présents
+    - name: List installed packages
+      run: pip freeze  # Vérifier que les bonnes versions des packages sont installées
 
     - name: Test with pytest
       run: |
-        pytest -vv || echo "Pytest failed"
+        pytest -vv test_session.py || echo "Pytest failed"
+        python test_python.py
